/*****************************************************************************/
/*                      BEGIN libcdada AUTOGENERATED C++ file                */
/*****************************************************************************/
// File autogenerated from cmd: ['/home/toto/Projects/libcdada/tools/cdada-gen', 'list:nf9_fwstatus', '-o', '/home/toto/Projects/pmacct_nf9_fwstatus/autogen_cdada_nf9_fwstatus.cc']
// Add your header includes for types {'nf9_fwstatus'} here

#include "cdada_types/nf9_fwdstatus.h"

///////////////////////////////////////////////////////////////////////////////
///                       DO NOT MODIFY AFTER THIS LINE                     ///
///////////////////////////////////////////////////////////////////////////////

#include <string.h>
#include <cdada/list_custom_cc.h>
#include <cdada/map_custom_cc.h>
#include <cdada/queue_custom_cc.h>
#include <cdada/set_custom_cc.h>
#include <cdada/stack_custom_cc.h>

//C++ comparison operators for user stypes (memcmp)

inline bool operator<(const nf9_fwstatus & a1, const nf9_fwstatus & a2){
    return memcmp((const void*)&a1, (const void*)&a2,
                                        sizeof( nf9_fwstatus )) < 0;
}
inline bool operator==(const nf9_fwstatus & a1, const nf9_fwstatus & a2){
    return memcmp((const void*)&a1, (const void*)&a2,
                                        sizeof( nf9_fwstatus )) == 0;
}

//Cdata wrappers

//BEGIN list for nf9_fwstatus (std::list<nf9_fwstatus>)


//Operator
void __cdada_list_autogen_create_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	s->list.custom = (void*)new std::list<nf9_fwstatus>();
}
void __cdada_list_autogen_destroy_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	delete p;
}
void __cdada_list_autogen_clear_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	p->clear();
}
bool __cdada_list_autogen_empty_nf9_fwstatus (const void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return p->empty();
}
uint32_t __cdada_list_autogen_size_nf9_fwstatus (const void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return p->size();
}
int __cdada_list_autogen_insert_nf9_fwstatus (void* m, const void* val,
						const uint32_t pos){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_insert_u<nf9_fwstatus> (s, p, val, pos);
}
int __cdada_list_autogen_get_nf9_fwstatus (const void* m, const uint32_t pos,
						void* val){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_get_u<nf9_fwstatus> (s, p, pos, val);
}
int __cdada_list_autogen_first_last_nf9_fwstatus (const void* m, bool first,
						void* key){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_first_last_u<nf9_fwstatus> (s, p, first, key);
}
int __cdada_list_autogen_erase_nf9_fwstatus (void* m, const uint32_t pos){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_erase_u<nf9_fwstatus> (s, p, pos);
}
int __cdada_list_autogen_remove_nf9_fwstatus (void* m, const void* val){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_remove_u<nf9_fwstatus> (s, p, val);
}
int __cdada_list_autogen_push_nf9_fwstatus (void* m, const void* val,
							bool front){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_push_u<nf9_fwstatus> (s, p, val, front);
}
int __cdada_list_autogen_pop_nf9_fwstatus (void* m, bool front){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_pop_u<nf9_fwstatus> (s, p, front);
}
void __cdada_list_autogen_sort_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	p->sort();
}
void __cdada_list_autogen_reverse_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	p->reverse();
}
void __cdada_list_autogen_unique_nf9_fwstatus (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	p->unique();
}
void __cdada_list_autogen_traverse_nf9_fwstatus (const void* m,
						cdada_list_it f,
						void* opaque){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_traverse_u<nf9_fwstatus> (s, p, f, opaque);
}
void __cdada_list_autogen_rtraverse_nf9_fwstatus (const void* m,
						cdada_list_it f,
						void* opaque){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<nf9_fwstatus>* p =
			(std::list<nf9_fwstatus>*)s->list.custom;
	return cdada_list_rtraverse_u<nf9_fwstatus> (s, p, f, opaque);
}
void __cdada_list_autogen_dump_nf9_fwstatus (const void* m,
                                                std::stringstream& ss){
        __cdada_list_int_t* s = (__cdada_list_int_t*)m;
        std::list<nf9_fwstatus>* p =
                        (std::list<nf9_fwstatus>*)s->list.custom;
        return cdada_list_dump_u< nf9_fwstatus > (s, p, ss);
}
__cdada_list_ops_t __cdada_list_autogen_nf9_fwstatus = {
	__cdada_list_autogen_create_nf9_fwstatus,
	__cdada_list_autogen_destroy_nf9_fwstatus,
	__cdada_list_autogen_clear_nf9_fwstatus,
	__cdada_list_autogen_empty_nf9_fwstatus,
	__cdada_list_autogen_size_nf9_fwstatus,
	__cdada_list_autogen_insert_nf9_fwstatus,
	__cdada_list_autogen_get_nf9_fwstatus,
	__cdada_list_autogen_first_last_nf9_fwstatus,
	__cdada_list_autogen_erase_nf9_fwstatus,
	__cdada_list_autogen_remove_nf9_fwstatus,
	__cdada_list_autogen_push_nf9_fwstatus,
	__cdada_list_autogen_pop_nf9_fwstatus,
	__cdada_list_autogen_sort_nf9_fwstatus,
	__cdada_list_autogen_reverse_nf9_fwstatus,
	__cdada_list_autogen_unique_nf9_fwstatus,
	__cdada_list_autogen_traverse_nf9_fwstatus,
	__cdada_list_autogen_rtraverse_nf9_fwstatus,
	__cdada_list_autogen_dump_nf9_fwstatus,
};

//END list for nf9_fwstatus (std::list<nf9_fwstatus>)

/*****************************************************************************/
/*                       END libcdada AUTOGENERATED C++ file                 */
/*****************************************************************************/
